package com.linkered.betterminecarts;

import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;

/**
 * Tags added by the mod. Their contents are generated by the data generator and can be changed by data packs.
 */
public final class ModTags {
	/**
	 * Items that couple two minecarts together. Contains {@code #minecraft:chains} by default.
	 */
	public static final TagKey<Item> MINECART_COUPLERS = TagKey.create(Registries.ITEM, BetterMinecarts.id("minecart_couplers"));

	private ModTags() {
	}
}
